matrix:
  include:

    ################ Linux Build ################

    - name: Linux
      os: linux
      dist: xenial

      addons:
        apt:
          packages:
            - libsdl2-dev
            - premake4

      before_install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip
    
      script:
        - make config=release
        - ./tools/package/itch/package.sh

    ################ OSX Build ################

    - name: OSX
      os: osx

      addons:
        homebrew:
          packages:
            - sdl2

      before_install:
        - curl -L -o premake.tar.gz http://sourceforge.net/projects/premake/files/Premake/4.4/premake-4.4-beta5-macosx.tar.gz/download && tar xvzf premake.tar.gz
        - curl -L -o butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default && unzip butler.zip

      script:
        - make config=release
        - ./tools/package/itch/package.sh

################ Common ################

language: c

compiler:
  - gcc

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - export PATH=$TRAVIS_BUILD_DIR:$PATH

before_script:
  - premake4 gmake

after_success:
  - cd package
  - butler validate virtualxt
  - butler login
  - butler push virtualxt phix/virtualxt:$TRAVIS_OS_NAME --userversion 0.0.1.${TRAVIS_BUILD_ID}