dist: bionic

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
      - libsdl2-dev
      - premake4
      - 7zip

install:
  - curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
  - 7z x butler.zip

before_script: 
  - premake4 gmake

script: 
  - make config=release

after_success:
  - ./tools/package/itch/package.sh
  - cd package
  
  - butler validate virtualxt
  - butler login
  - butler push virtualxt phix/virtualxt:linux --userversion 0.0.1.$TRAVIS_BUILD_ID