matrix:
  include:

    ################ Linux Build ################

    - name: Linux
      os: linux
      dist: xenial

      addons:
        apt:
          packages:
            - libsdl2-dev
            - premake4

      before_install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip
    
      script:
        - make config=release
        - ./tools/package/itch/package.sh

    ################ OSX Build ################

    - name: OSX
      os: osx

      addons:
        homebrew:
          packages:
            - sdl2

      before_install:
        - curl -L -o premake.tar.gz http://sourceforge.net/projects/premake/files/Premake/4.4/premake-4.4-beta5-macosx.tar.gz/download && tar xvzf premake.tar.gz
        - curl -L -o butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default && unzip butler.zip

        - curl -L -o sdl.dmg https://www.libsdl.org/release/SDL2-2.0.10.dmg && hdiutil attach sdl.dmg
        - cp -r /Volumes/SDL2/SDL2.framework /Library/Frameworks

      script:
        - make config=release
        - ./tools/package/itch/package.sh

    ################ Windows Build ################

    - name: Windows
      os: windows

      before_install:
        - curl -L -o premake.zip http://sourceforge.net/projects/premake/files/Premake/4.4/premake-4.4-beta5-windows.zip/download && unzip premake.zip
        - curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default && unzip butler.zip

        - curl -L -o sdl.tar.gz https://www.libsdl.org/release/SDL2-devel-2.0.10-mingw.tar.gz
        - 7z x sdl.tar.gz && 7z x sdl.tar

        - export C_INCLUDE_PATH=${TRAVIS_BUILD_DIR}/SDL2-2.0.10/x86_64-w64-mingw32/include
        - export LIBRARY_PATH=${TRAVIS_BUILD_DIR}/SDL2-2.0.10/x86_64-w64-mingw32/lib

        - choco install make

      script:
        - make config=release
        - ./tools/package/itch/package.bat

################ Common ################

language: c

compiler:
  - gcc

env:
  - VXT_VERSION=0.0.1

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - export PATH=$TRAVIS_BUILD_DIR:$PATH

before_script:
  - premake4 gmake

after_success:
  - cd package
  - butler validate virtualxt
  - butler login
  - butler push virtualxt phix/virtualxt:$TRAVIS_OS_NAME --userversion ${VXT_VERSION}.${TRAVIS_BUILD_ID}