dist: bionic

language: c

compiler:
  - gcc

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libsdl2-dev
      - premake4

install:
  - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
  - unzip butler.zip

before_script: 
  - premake4 gmake

script: 
  - make config=release

after_success:
  - ./tools/package/itch/package.sh
  - cd package

  - $TRAVIS_BUILD_DIR/butler validate virtualxt
  - $TRAVIS_BUILD_DIR/butler login
  - $TRAVIS_BUILD_DIR/butler push virtualxt phix/virtualxt:linux --userversion 0.0.1.$TRAVIS_BUILD_ID