version: 0.0.1.{build}

platform: x64

branches:
  only:
  - master

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

install:
  - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
  - curl -L -o premake.zip http://sourceforge.net/projects/premake/files/Premake/4.4/premake-4.4-beta5-windows.zip/download
  - 7z x premake.zip
  - curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
  - 7z x butler.zip

build_script:
  - premake4 gmake --nosdl
  - mingw32-make config=release

after_build:
  - tools\package\itch\package.bat
  - cd package
  - butler validate virtualxt
  - butler login
  - butler push virtualxt phix/virtualxt:windows --userversion %APPVEYOR_BUILD_VERSION%
