version: 0.0.1.{build}

platform: x64

branches:
  only:
  - master

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

install:
  - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\bin;%PATH%
  #- appveyor DownloadFile http://sourceforge.net/projects/premake/files/Premake/4.4/premake-4.4-beta5-windows.zip/download
  #- 7z x premake-4.4-beta5-windows.zip

build_script:
  - .\tools\build\premake4\premake4.exe gmake
  - make config=release
  - cd C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1
  - dir

artifacts:
  - path: virtualxt.exe