[[actions]]
name = "Boot FreeDOS"
path = "VirtualXT.app"
args = ["-a", "VirtualXT.app/Contents/Resources/freedos.img"]

[[actions]]
name = "Boot Floppy Image"
path = "VirtualXT.app"

[[actions]]
name = "manual"
path = "VirtualXT.app/Contents/Resources/manual/index.html"