[[actions]]
name = "Boot FreeDOS"

#TODO: Fix this! Passing arguments to app bundle seems to be a problem.

#path = "VirtualXT.app"
#args = ["-a", "VirtualXT.app/Contents/Resources/freedos.img"]
path = "VirtualXT.app/Contents/MacOS/start.sh"
args = ["-a", "../Resources/freedos.img"]

[[actions]]
name = "Boot Floppy Image"
path = "VirtualXT.app"

[[actions]]
name = "manual"
path = "VirtualXT.app/Contents/Resources/manual/index.html"