#!/bin/bash

if [ "$(uname)" == "Darwin" ]; then
    HERE="$(dirname $(pwd -P $0)/${0#\.\/})"
    cd $HERE
    exec ./virtualxt "$@"
else
    HERE="$(dirname "$(readlink -f "${0}")")"
    export LD_LIBRARY_PATH=${HERE}/lib:$LD_LIBRARY_PATH
    exec "${HERE}/bin/virtualxt" "$@"
fi