[[actions]]
name = "Boot FreeDOS"
path = "virtualxt.exe"
console = true
args = ["-f", "freedos.img"]

[[actions]]
name = "Boot Floppy Image"
path = "virtualxt.exe"
console = true

[[actions]]
name = "manual"
path = "README.md"